<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>AnyCPU;x86</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\WmsGfxSpriteEditor.Palettes\WmsGfxSpriteEditor.Palettes.csproj" />
    <ProjectReference Include="..\WmsGfxSpriteEditor.Roms\WmsGfxSpriteEditor.Roms.csproj" />
    <ProjectReference Include="..\WmsGfxSpriteEditor.Sprites\WmsGfxSpriteEditor.Sprites.csproj" />
  </ItemGroup>

</Project>
