using System.Drawing;

namespace WmsGfxSpriteEditor.Sprites
{
    public interface ISprite
    {
        // We use Memory<byte> so that we can share memory between the Sprite being edited and the MemoryStream it originates from
        Memory<byte> PixelData { get; }

        /// <summary>
        /// Custom tag for the sprite, can be used to store additional information
        /// </summary>
        object Tag { get; set; }

        /// <summary>
        /// Index of the sprite in the ROM data (generated by system - not held in ROM)
        /// </summary>
        int SpriteIndex { get; }

        int BitsPerPixel { get; }
        int Width { get; }
        int WidthInBytes { get; }
        int Height { get; }
        Size Size => new(Width, Height);

        Color[] Palette { get; }

        bool IsLinear { get; }

        bool IsPixelDataDirty { get; }

        void ClearPixelDataDirtyFlag();

        bool IsInBounds(int x, int y);

        int GetPaletteIndexFromPixel(int x, int y);

        void SetPixelByPaletteIndex(int x, int y, int paletteIndex);

        void XFlip();

        void YFlip();

        void ShiftPixelsUp();

        void ShiftPixelsDown();

        void ShiftPixelsLeft();

        void ShiftPixelsRight();

        byte[] ClonePixelData();

        UInt128 GetPixelDataHash();

        Bitmap CreateBitmapFromSprite();
    }
}