using System.Drawing;

namespace WmsGfxSpriteEditor.Sprites
{
    /// <summary>
    /// Represents a sprite and provides methods for pixel manipulation, flipping, shifting, and data access.
    /// </summary>
    public interface ISprite
    {
        /// <summary>
        /// Gets the pixel data for the sprite. Memory<byte> allows sharing memory between the sprite and its source stream.
        /// </summary>
        Memory<byte> PixelData { get; }

        /// <summary>
        /// Custom tag for the sprite, can be used to store additional information.
        /// </summary>
        object Tag { get; set; }

        /// <summary>
        /// Index of the sprite in the ROM data (generated by system - not held in ROM).
        /// </summary>
        int SpriteIndex { get; }

        /// <summary>
        /// Gets the number of bits per pixel for the sprite.
        /// </summary>
        int BitsPerPixel { get; }

        /// <summary>
        /// Gets the width of the sprite in pixels.
        /// </summary>
        int Width { get; }

        /// <summary>
        /// Gets the width of the sprite in bytes.
        /// </summary>
        int WidthInBytes { get; }

        /// <summary>
        /// Gets the height of the sprite in pixels.
        /// </summary>
        int Height { get; }

        /// <summary>
        /// Gets the size of the sprite as a <see cref="Size"/> structure.
        /// </summary>
        Size Size => new(Width, Height);

        /// <summary>
        /// Gets the color palette used by the sprite.
        /// </summary>
        Color[] Palette { get; }

        /// <summary>
        /// Gets a value indicating whether the sprite uses linear pixel layout.
        /// </summary>
        bool IsLinear { get; }

        /// <summary>
        /// Gets a value indicating whether the pixel data has been modified.
        /// </summary>
        bool IsPixelDataDirty { get; }

        /// <summary>
        /// Clears the pixel data dirty flag.
        /// </summary>
        void ClearPixelDataDirtyFlag();

        /// <summary>
        /// Determines whether the specified coordinates are within the bounds of the sprite.
        /// </summary>
        /// <param name="x">The X coordinate.</param>
        /// <param name="y">The Y coordinate.</param>
        /// <returns>True if the coordinates are in bounds; otherwise, false.</returns>
        bool IsInBounds(int x, int y);

        /// <summary>
        /// Gets the palette index for the pixel at the specified coordinates.
        /// </summary>
        /// <param name="x">The X coordinate.</param>
        /// <param name="y">The Y coordinate.</param>
        /// <returns>The palette index.</returns>
        int GetPaletteIndexFromPixel(int x, int y);

        /// <summary>
        /// Sets the pixel at the specified coordinates to the given palette index.
        /// </summary>
        /// <param name="x">The X coordinate.</param>
        /// <param name="y">The Y coordinate.</param>
        /// <param name="paletteIndex">The palette index to set.</param>
        void SetPixelByPaletteIndex(int x, int y, int paletteIndex);

        /// <summary>
        /// Flips the sprite horizontally.
        /// </summary>
        void XFlip();

        /// <summary>
        /// Flips the sprite vertically.
        /// </summary>
        void YFlip();

        /// <summary>
        /// Shifts all pixels up by one row.
        /// </summary>
        void ShiftPixelsUp();

        /// <summary>
        /// Shifts all pixels down by one row.
        /// </summary>
        void ShiftPixelsDown();

        /// <summary>
        /// Shifts all pixels left by one column.
        /// </summary>
        void ShiftPixelsLeft();

        /// <summary>
        /// Shifts all pixels right by one column.
        /// </summary>
        void ShiftPixelsRight();

        /// <summary>
        /// Creates a copy of the pixel data as a byte array.
        /// </summary>
        /// <returns>A copy of the pixel data.</returns>
        byte[] ClonePixelData();

        /// <summary>
        /// Gets a hash value representing the current pixel data.
        /// </summary>
        /// <returns>The pixel data hash.</returns>
        UInt128 GetPixelDataHash();

        /// <summary>
        /// Creates a <see cref="Bitmap"/> representation of the sprite.
        /// </summary>
        /// <returns>A bitmap of the sprite.</returns>
        Bitmap CreateBitmapFromSprite();
    }
}