namespace WmsGfxSpriteEditor.Sprites
{
    /// <summary>
    /// Represents information about a sprite in the ROM data
    /// </summary>
    public record SpriteInfo(
#pragma warning disable SA1313 // Parameter names should begin with lower-case letter
        int Index,
        string Name,
        int Offset,
        int WidthInBytes,
        int Height,
        int BitsPerPixel,
        bool IsLinear = true)
#pragma warning restore SA1313 // Parameter names should begin with lower-case letter
    {
        /// <summary>
        /// Zero-based index of the sprite (generated by system - not held in ROM)
        /// </summary>
        public int Index { get; init; } = Index >= 0 ? Index : throw new ArgumentOutOfRangeException(nameof(Index), "Index must be a non-negative integer");

        /// <summary>
        /// Gets the name of the sprite
        /// </summary>
        public string Name { get; init; } = Name ?? throw new ArgumentNullException(nameof(Name));

        /// <summary>
        /// Gets the offset of the sprite data in the memory stream
        /// </summary>
        public int Offset { get; init; } = Offset;

        /// <summary>
        /// Gets the width of the sprite in bytes (each byte contains 2 pixels)
        /// </summary>
        public int WidthInBytes { get; init; } = WidthInBytes > 0 ? WidthInBytes : throw new ArgumentOutOfRangeException(nameof(WidthInBytes), "Width in bytes must be greater than 0");

        /// <summary>
        /// Gets the width of the sprite in pixels (WidthInBytes * 2)
        /// </summary>
        public int WidthInPixels => WidthInBytes * 2;

        /// <summary>
        /// Gets the height of the sprite in pixels
        /// </summary>
        public int Height { get; init; } = Height > 0 ? Height : throw new ArgumentOutOfRangeException(nameof(Height), "Height must be greater than 0");

        /// <summary>
        /// Gets the bits per pixel in the sprite
        /// </summary>
        public int BitsPerPixel { get; init; } = BitsPerPixel > 0 ? BitsPerPixel : throw new ArgumentOutOfRangeException(nameof(BitsPerPixel), "Bits per pixel must be greater than 0");

        /// <summary>
        /// Gets whether the sprite data is stored in a linear format
        /// </summary>
        public bool IsLinear { get; init; } = IsLinear;

        /// <summary>
        /// Returns a string representation of the sprite information
        /// </summary>
        /// <returns>A string containing the sprite name, offset, and dimensions</returns>
        public override string ToString() => $"{Name} (0x{Offset:X4}) [{WidthInPixels}x{Height}]";
    }
}