<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Platforms>AnyCPU;x86</Platforms>
    <ApplicationIcon>hulk-fancy.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="History\**" />
    <EmbeddedResource Remove="History\**" />
    <None Remove="History\**" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="hulk-fancy.ico" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WmsGfxSpriteEditor.Roms.Robotron2084\WmsGfxSpriteEditor.Roms.Robotron2084.csproj" />
    <ProjectReference Include="..\WmsGfxSpriteEditor.Roms\WmsGfxSpriteEditor.Roms.csproj" />
    <ProjectReference Include="..\WmsGfxSpriteEditor.Sprites\WmsGfxSpriteEditor.Sprites.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>